id: P000513
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 2021-12-16 15:43:49.868784
source_metadata:
  id: bdr:W1KG5761
  title: བོད་ཀྱི་དེབ་ཐེར་དཔྱིད་ཀྱི་རྒྱལ་མོའི་གླུ་དབྱངས་
  author: ''
  volumes:
    9d5af2fa9e554ecc91faf626778888db:
      image_group_id: I1KG10661
      title: Volume 1 of rig 'dzin 'ja' tshon snying po'i gter chos yongs rdzogs bka'
        'bum dang bcas pa'i lung gi thog yig skal bzang dad brgya'i pad+mo kun nas
        dgyes pa'i bshes gnyen sogs/
      volume_number: 1
      total_pages: 282
    b4b9484e128e4fdaa54bd251a3097014:
      image_group_id: I1KG10662
      title: Volume 2 of rig 'dzin 'ja' tshon snying po'i gter chos yongs rdzogs bka'
        'bum dang bcas pa'i lung gi thog yig skal bzang dad brgya'i pad+mo kun nas
        dgyes pa'i bshes gnyen sogs/
      volume_number: 2
      total_pages: 314
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
